package WebCA::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'WebCA::Schema',

    connect_info => {
        dsn => 'dbi:Pg:webca',
        user => 'webca',
        password => 'webca',
    }
);

=head1 NAME

WebCA::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<WebCA>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<WebCA::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.65

=head1 AUTHOR

Александр Фролов

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
